version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: mau
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mau@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: 123
    ports: 
      - 5000:80